include:
- fission.py
kind: ArchiveUploadSpec
name: fission-py-PcLu

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: wtc-list-fix-remove-fn-331d23fa-ee27-4730-8489-b985856f0cb1
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://fission-py-PcLu
  environment:
    name: wtc-list-fix-remove-env
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2023-01-16T16:21:26Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: wtc-list-fix-remove-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 3
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 0
      hpaMetrics:
      - resource:
          name: cpu
          target:
            averageUtilization: 80
            type: Utilization
        type: Resource
    StrategyType: execution
  concurrency: 500
  environment:
    name: wtc-list-fix-remove-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: wtc-list-fix-remove-fn-331d23fa-ee27-4730-8489-b985856f0cb1
      namespace: default
  requestsPerPod: 10000
  resources: {}
